### ISSUE TITLE
Update to mime@2.0.3

### ISSUE THREAD

**Issue by pigulla** [google/node-gtoken#15]
The version of [mime](https://github.com/broofa/node-mime) used by gtoken has a known [security vulnerability](https://nodesecurity.io/advisories/535). Please update the dependency to version 2.0.3 or later.

**Comment by ofrobots** [comment]
Thanks for reporting. I think we will need to upgrade to 1.4.1 the 2.x branch requires node 6+ but we still want to support node 4.
