### ISSUE TITLE
Drop dependency on request

### ISSUE THREAD

**Issue by ofrobots** [google/node-gtoken#19]
Request is really bulky for such a tiny library, and we are trying to get rid of it from the entire stack of modules we use on Google Cloud Platform. We should replace it with another module that is lighter, and for bonus points, works transparently in the browser.

**Comment by JustinBeckwith** [comment]
A few options to consider here:
- [node-fetch](https://github.com/bitinn/node-fetch) - closely matches the browser fetch API, has 0 runtime dependencies, supports Promise/async style APIs. 
- [axios](https://github.com/axios/axios) - async/promise based API, *very* few dependencies, lots of contributors, works same in the browser as the node
- [got](https://github.com/sindresorhus/got) - async/promise based API, a fair number of deps, and doesn't appear to be browser friendly

I would be ok with `node-fetch` or `axios`.  Thoughts?

**Comment by ofrobots** [comment]
Adding @jmdobry.

**Comment by ofrobots** [comment]
While I don't have practical experience with axios and node-fetch, those look like good candidates indeed. I have heard anecdotal reports that node-fetch may be a bit low-level, but I haven't looked at the API myself.

**Comment by jmdobry** [comment]
I'm for `node-fetch` or `axios`.

**Comment by jmdobry** [comment]
I'm for `node-fetch` or `axios`.

**Comment by JustinBeckwith** [comment]
Fixed in #23
