### ISSUE TITLE
Push a new npm module

### ISSUE THREAD

**Issue by JustinBeckwith** [google/node-gtoken#29]
It would be great to have 1.0 pushed so we can use the d.ts and async API over in the auth client.

**Comment by ofrobots** [comment]
I am guessing you meant 2.0.

**Comment by JustinBeckwith** [comment]
Nah, I'm sending this one back to 1.0.  :)  Yes I should have said 2.0 :)

**Comment by JustinBeckwith** [comment]
@ofrobots I think we're pretty much done with this module for now.  Once this gets pushed, I'll be able to update it in google-auth-library-nodejs along with the types 😄

**Comment by ofrobots** [comment]
Done. https://github.com/google/node-gtoken/releases/tag/v2.0.0
